import { tasksRepo, fixedEventsRepo } from './repositories';
import { generateId } from '@/src/utils/id';
import { addDays, startOfDay, toISO } from '@/src/utils/date';
import type { FixedEvent, Task } from '@/src/types';

export async function seedSampleData(): Promise<void> {
  const today = startOfDay(new Date());
  const tomorrow = addDays(today, 1);

  const fixedAppointment: FixedEvent = {
    id: generateId('fixed'),
    title: 'Dentist appointment',
    start: toISO(setTime(today, 14, 0)),
    end: toISO(setTime(today, 15, 0)),
    location: 'Downtown clinic',
    isAllDay: false,
    importedAt: new Date().toISOString(),
  };

  const tasks: Task[] = [
    {
      id: generateId('task'),
      title: 'Finish homepage design',
      notes: 'High-priority deadline task',
      status: 'planned',
      priority: 'high',
      estimatedDurationMinutes: 120,
      remainingDurationMinutes: 120,
      deadline: toISO(addDays(today, 2)),
      preferredTimeOfDay: 'morning',
      energyRequirement: 'high',
      context: 'computer',
      projectOrCategory: 'Website',
      splittable: true,
      minimumChunkMinutes: 30,
      maximumChunkMinutes: 120,
      dependencyIds: [],
      isFixed: false,
      nonNegotiable: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: generateId('task'),
      title: 'Work out',
      notes: 'Three times this week',
      status: 'planned',
      priority: 'medium',
      estimatedDurationMinutes: 45,
      remainingDurationMinutes: 45,
      preferredTimeOfDay: 'morning',
      energyRequirement: 'high',
      context: 'home',
      projectOrCategory: 'Health',
      splittable: false,
      minimumChunkMinutes: 45,
      dependencyIds: [],
      isFixed: false,
      nonNegotiable: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: generateId('task'),
      title: 'Call insurance company',
      notes: 'Administrative call',
      status: 'inbox',
      priority: 'medium',
      estimatedDurationMinutes: 30,
      remainingDurationMinutes: 30,
      deadline: toISO(tomorrow),
      preferredTimeOfDay: 'afternoon',
      energyRequirement: 'low',
      context: 'phone',
      projectOrCategory: 'Admin',
      splittable: false,
      minimumChunkMinutes: 15,
      dependencyIds: [],
      isFixed: false,
      nonNegotiable: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: generateId('task'),
      title: 'Draft proposal',
      notes: 'Deep creative work',
      status: 'planned',
      priority: 'high',
      estimatedDurationMinutes: 90,
      remainingDurationMinutes: 90,
      preferredTimeOfDay: 'morning',
      energyRequirement: 'high',
      context: 'creative',
      projectOrCategory: 'Client',
      splittable: true,
      minimumChunkMinutes: 30,
      maximumChunkMinutes: 90,
      dependencyIds: [],
      isFixed: false,
      nonNegotiable: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: generateId('task'),
      title: 'Grocery run',
      notes: 'Errand',
      status: 'planned',
      priority: 'low',
      estimatedDurationMinutes: 60,
      remainingDurationMinutes: 60,
      preferredTimeOfDay: 'evening',
      energyRequirement: 'low',
      context: 'errands',
      projectOrCategory: 'Home',
      splittable: false,
      minimumChunkMinutes: 30,
      dependencyIds: [],
      isFixed: false,
      nonNegotiable: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: generateId('task'),
      title: 'Weekly review',
      notes: 'Recurring routine',
      status: 'planned',
      priority: 'medium',
      estimatedDurationMinutes: 30,
      remainingDurationMinutes: 30,
      preferredTimeOfDay: 'afternoon',
      energyRequirement: 'medium',
      context: 'administrative',
      projectOrCategory: 'Review',
      splittable: false,
      minimumChunkMinutes: 15,
      recurrenceRule: { frequency: 'weekly' },
      dependencyIds: [],
      isFixed: false,
      nonNegotiable: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: generateId('task'),
      title: 'Impossible 8-hour task today',
      notes: 'Will not fit',
      status: 'planned',
      priority: 'high',
      estimatedDurationMinutes: 480,
      remainingDurationMinutes: 480,
      deadline: toISO(today),
      preferredTimeOfDay: 'morning',
      energyRequirement: 'high',
      context: 'computer',
      projectOrCategory: 'Overload',
      splittable: true,
      minimumChunkMinutes: 60,
      maximumChunkMinutes: 240,
      dependencyIds: [],
      isFixed: false,
      nonNegotiable: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: generateId('task'),
      title: 'Prepare slides',
      notes: 'Depends on proposal draft',
      status: 'planned',
      priority: 'medium',
      estimatedDurationMinutes: 60,
      remainingDurationMinutes: 60,
      preferredTimeOfDay: 'afternoon',
      energyRequirement: 'medium',
      context: 'computer',
      projectOrCategory: 'Client',
      splittable: true,
      minimumChunkMinutes: 20,
      dependencyIds: [],
      isFixed: false,
      nonNegotiable: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  for (const task of tasks) {
    await tasksRepo.save(task);
  }
  await fixedEventsRepo.save(fixedAppointment);
}

function setTime(date: Date, hours: number, minutes: number): Date {
  const d = new Date(date);
  d.setHours(hours, minutes, 0, 0);
  return d;
}
